### ISSUE TITLE
Assignment 3

### ISSUE THREAD

**Issue by blackboxlogic** [JonMallozzi/cos470#3]
This... won't detect an intersection between just before midnight and just after midnight.
https://github.com/JonMallozzi/cos470/blob/1e3c28009a9aedf181cccd06f32502a61823665d/Assignment3/metCheckingLogic.cs#L32

This... only looks for exact matches which doesn't happen
https://github.com/JonMallozzi/cos470/blob/1e3c28009a9aedf181cccd06f32502a61823665d/Assignment3/metCheckingLogic.cs#L60-L65

**Comment by blackboxlogic** [comment]
There isn't enough here for me to grade when I check out your code. I'm looking at the HEAD of branch Assignment3. The Solution file won't load, and I don't see any .csproj files.
I want to run your units tests and your API.

**Comment by JonMallozzi** [comment]
all .csproj files should now be in the repro for all projects

**Comment by blackboxlogic** [comment]
Your project doesn't compile. And when I fix it so it compiles, the tests don't run. I suspect because their target framework is ".net framework" instead of "core".

**Comment by JonMallozzi** [comment]
Sorry, I removed the code that got pushed by mistake when adding the .csproj files which made it not compile. Also, I swapped the tests over to a .core project. Hopefully, that fixes it and if any more issues come up feel free to let me know.

**Comment by blackboxlogic** [comment]
### Data model
yes
### Business logic
Some of your I's should be J's
There are not 40000 MS in a minute.
The configurable-ness of the API doesn't have meaningful units: -2pts
### Tests
You only tested positive matches in your unit tests.
### Api
Yep
### Organization
You don't want properties\ in the gitingnore. - 3pts

**Comment by blackboxlogic** [comment]
I see you've fixed the gitignore. I've updated the grade.

**Comment by blackboxlogic** [comment]
And I see you've fixed the units. +2 points
